version: "3.8"

services:
  appointments_ms:
    container_name: appointments_ms 
    image: appointments_ms_img 
    build:
      context: .
      target: appointment_ms
      dockerfile: ./Dockerfile
    environment:
      - PORT=8081
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=medisyncdb
    ports:
      - 8081:8081
    networks:
      - medisync-appointments-network
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: appointments_db
    image: postgres:15.4-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medisyncdb
    ports:
      - 5432:5432
    networks:
      - medisync-appointments-network


networks:
  medisync-appointments-network:
